//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleMVCProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Item
    {
        [Key]
        public int Id { get; set; }
        public string Username { get; set; }
        public string Place { get; set; }
        public string DateOfTravel { get; set; }
        public string FlightName { get; set; }
        public string FlightCost { get; set; }
        public string Website { get; set; }
    }
}
